### ISSUE TITLE
Home Assistant+Myserver1+K4500C

### ISSUE THREAD

**Issue by blademckain** [sdomotica/hassio-addons#1]
Hello,
I wanted to know if mounting a Living Now smart system with the K4500C + MyServer1 then I could control everything via Home assistant

**Comment by sdomotica** [comment]
K4500C is wireless (Zigbee custom) Living Now.   Myserver1 is wired Living Now. These systems don't works togheter in BTicino. Are two different solutions.
For Myserver1, with my addon, you can integrate in Home Assistant.
The K4500C is in development by us.
Bye
Sandro
