### ISSUE TITLE
64bit version

### ISSUE THREAD

**Issue by fiserail** [sdomotica/hassio-addons#2]
I'm trying to insall this addon but it is compatibile only with 32bit hass.io version.
I'm using a virtual machine and because of hassio depends on Docker i cannot install the 32bit version.

Are you thinking to develop a 64 bit version of your add-on also?

**Comment by sdomotica** [comment]
In this moment, the addon is only for 32bit and raspberry. I planned for the end of 2019 the addon for 64bit and other platform.
