### ISSUE TITLE
K4500C Integration

### ISSUE THREAD

**Issue by xefil** [sdomotica/hassio-addons#3]
Hello,

Does it work with K4500C Gateway or still in devel?

Any Roadmap?

Thanks!

Simon

**Comment by sdomotica** [comment]
Addon com8ng soon, if would you use right now, there is Sdomotica with home assistant core in venv and the Gateway already implemented 

https://www.facebook.com/100011452626594/posts/1224699357921807/

https://www.dropbox.com/s/nymevo518eoz0x8/Sdomotica%20%E2%80%93%20Works%20with%20Legrand%20-%20LivingNow.pdf?dl=1

https://www.facebook.com/100011452626594/posts/1225378067853936/

Bye
Sandro

**Comment by xefil** [comment]
Ciao Sandro!
Il gateway ancora non è installato, auspico di metterlo in linea per i primi di settembre, quando entrerò nella nuova casa.
Avendo HA in docker su NAS Synology, non mi è chiaro se quanto indicato dovrebbe sostituire il setup attuale (leggo di SD immagine da zero)
Casomai tempistiche per il GW o consigli?

Grazie!! :-)

Simone

**Comment by sdomotica** [comment]
L’immagine è per raspberry pi 2 e 3, anche quando rilascerò addon sarà solo per raspberry.
Mi viene difficile mantenere un tipo di hardware. Ma magari un giorno potrei provare anche i synology.
A presto
Sandro

**Comment by xefil** [comment]
Assolutamente comprensibile!
Mi chiedevo se c’era la possibilità d’avere solo la parte di addon come custom_components ma ammetto che devo ancora leggermi meglio la documentazione. Un RPi lo ho a disposizione ma vorrei evitare farci girare su tutto HA :-)
Se invece li sopra gira solo la tua parte di codice e posso mantenere l’HA sul nas sarebbe già molto buono!

Grazie!

Simone

**Comment by xefil** [comment]
Ciao @sdomotica (Sandro),
Qualche novità col componente dedicato? Non posso (voglio) slegarmi da HA su Synology. Casomai potrei installare anche il RPi e lasciarlo solo per questo scopo, ma potrebbe parlare con HA su Synology?
Grazie!

**Comment by sdomotica** [comment]
L'addon non è disponibile al momento, ma se usi su un raspberry la nostra immagine, poi basta che metti i nostri package nel tuo Home Assistant e puntare al broker mqtt presente in Sdomotica.
https://www.facebook.com/permalink.php?story_fbid=1224699357921807&id=100011452626594
Ciao
Sandro

**Comment by xefil** [comment]
Questo significa che quindi uso il mio Synology NAS con Home Assistant come sempre e punto al broker mqtt, tuttavia il problema è che ho già mosquitto per la gestione di device mqtt esterni.
Sai mica semplificarmi come è gestito il flow di comunicazione dei componenti?

```
device_BTicino <--zigbee--> K4500C <--WiFi--> Sdomotica <-- come? --> HomeAssistant
```

Crea delle entry MQTT che HomeAssistant poi può prelevare col solito discovery?

Infine mi dai qualche info e indicazioni di prezzi della licenza?

Grazie ancora!

Simone

**Comment by sdomotica** [comment]
Contattami sandro.dimarco   Chiocciola sdomotica.com    oppure Skype pfeifer-1968 o messenger Sdomotica Automation che ne parliamo a voce e ti spiego in dettaglio

**Comment by xefil** [comment]
Perfetto, ti ho scritto su skype :)
