### ISSUE TITLE
Biticino 3578 zigbee gateway support

### ISSUE THREAD

**Issue by Ikes72000** [sdomotica/hassio-addons#4]
Hello,

Does the zigbee gateway Bticino 3578 supported by your addon ?
Would it be possible ? 

Thanks. 

Ikes

**Comment by sdomotica** [comment]
HI Ikes, sorry the addon don't support right now and in the future the old zigbee system. 
Only the new Living Now Smart is coming soon.
Bye
Sandro

**Comment by Ikes72000** [comment]
Ok, thanks for your reply.

Ikes.
