### ISSUE TITLE
compatibilita con FC80GT 

### ISSUE THREAD

**Issue by nanni85** [sdomotica/hassio-addons#5]
Ciao Sandro,
mi chiedevo se Sdomotica è compatibile con il gateway FC80GT

Grazie

**Comment by sdomotica** [comment]
L'addon è solo per il bus, per il gateway Zigbee abbiamo la nostra immagine.
https://www.facebook.com/permalink.php?story_fbid=1224699357921807&id=100011452626594
Ciao
Sandro
