### ISSUE TITLE
SDOMOTICA HOME+CONTROL 2022

### ISSUE THREAD

**Issue by Murazor** [sdomotica/hassio-addons#8]
Buongiorno, sto provando gl iaddons. Ed ho notato che "Sdomotica Home + Control 2022" non crea le configurazioni degli oggetti impianto ma solo le programmazioni del riscaldamento.

**Comment by sdomotica** [comment]
Scrivimi via mail che ci accordiamo, mi collego via anydesk e verifichiamo cosa non vaa
mail sandrodimarco       libero.it

**Comment by Murazor** [comment]
Ciao. Stavo spulciando e sembra che per la Home + Control 2022 quello che fa parte del bus SCS non sia popolato. Per usare il Bus SCS quale addon devo usare? ho visto che ce ne sono 4 di cui uno solo dichiuarato deprecato...
Grazie.

**Comment by sdomotica** [comment]
C'è l'addon Sdomotica Bticino SCS.
Esattamente scritto così
CIao
Sandro
